Lone.page({
  components: [
    {
      name: 'test',
      template: `
        <div id="app">
          <h1>Page 1</h1>
          <ul>
            <li v-for="item in list">{{item}}</li>
          </ul>
          <button id="navigate-btn" style="color:red;" v-on:click="navigatorTo">navigatorTo: /test</button>
          <h2 :id="n" :style="{backgroundColor: 'red'}" style="color:blue;">N:{{ n }}</h2>
          <ad title="My journey with Lone" :n="n" @enlarge-text="test" :list="list" />
          <alert>I'm a Slot content.</alert>
          <alert></alert>
          <base-layout>
            <p slot="header">Slot Header</p>
            <p>Slot main content.</p>
            <p slot="footer">Slot Footer</p>
          </base-layout>
          <v-model />
        </div>
      `
    },
    {
      name: 'ad',
      template: `<div>我是广告{{n}} {{title}}, {{list}}</div>`
    },
    {
      name: 'alert',
      template: `<div style="padding:10px 0;"><slot>I'm a Slot default content.</slot></div>`
    },
    {
      name: 'base-layout',
      template: `
        <div style="padding:10px 0;background:#ccc;">
          <div class="container">
            <header>
              <slot name="header"></slot>
            </header>
            <main>
              <slot name="default"></slot>
            </main>
            <footer>
              <slot name="footer"></slot>
            </footer>
          </div>
        </div>
      `
    },
    {
      name: 'v-model',
      template: `<div style="background-color: aquamarine;">
        <input v-model="n">
        <p>you input is: {{n}}</p>
        <p @click="showModel" style="cursor: pointer;">click me show the input model on console.</p>
        <h3>textarea:</h3>
        <textarea v-model="message" placeholder="add multiple lines"></textarea>
        <br />
        <span>Multiline message is:{{ message }}</span>
        
        <h3>单个复选框，绑定到布尔值:</h3>
        <div>
          <input type="checkbox" id="checkbox" v-model="checked">
          <label for="checkbox">{{ checked }}</label>          
        </div>
        <h3>多个复选框，绑定到同一个数组：        </h3>
        <div id='example-3'>
          <input type="checkbox" id="jack" value="Jack" v-model="checkedNames">
          <label for="jack">Jack</label>
          <input type="checkbox" id="john" value="John" v-model="checkedNames">
          <label for="john">John</label>
          <input type="checkbox" id="mike" value="Mike" v-model="checkedNames">
          <label for="mike">Mike</label>
          <br>
          <span>Checked names: {{ checkedNames }}</span>
        </div>
        <h3>单选按钮</h3>
        <div id="example-4">
          <input type="radio" id="one" value="One" v-model="picked">
          <label for="one">One</label>
          <br>
          <input type="radio" id="two" value="Two" v-model="picked">
          <label for="two">Two</label>
          <br>
          <span>Picked: {{ picked }}</span>
        </div>
      </div>
      `
    },
    {
      name: 'test2',
      template: `<article uid="238" class="markdown-body "><button v-on:click="back">navigatorBack</button><h1 uid="239">Button</h1> <h2 uid="242">基础用法</h2> <h3 uid="245">不同主题</h3> <div uid="248" class="vue-demo-block"><div uid="249" class="vue-demo"><button uid="250" class="se-button se-button--default"><!---->默认按钮</button> <button uid="254" class="se-button se-button--primary"><!---->主要按钮</button> <button uid="258" class="se-button se-button--warn"><!---->警告按钮</button> <button uid="262" class="se-button se-button--danger"><!---->危险按钮</button></div> <div uid="266"></div> <pre uid="268" class="vue-demo-source-code"><code uid="269" class="language-html"><span uid="270" class="token tag"><span uid="271" class="token tag"><span uid="272" class="token punctuation">&lt;</span>se-button</span> <span uid="276" class="token attr-name">type</span><span uid="278" class="token attr-value"><span uid="279" class="token punctuation">=</span><span uid="281" class="token punctuation">"</span>default<span uid="284" class="token punctuation">"</span></span><span uid="286" class="token punctuation">&gt;</span></span>默认按钮<span uid="289" class="token tag"><span uid="290" class="token tag"><span uid="291" class="token punctuation">&lt;/</span>se-button</span><span uid="294" class="token punctuation">&gt;</span></span>
      <span uid="297" class="token tag"><span uid="298" class="token tag"><span uid="299" class="token punctuation">&lt;</span>se-button</span> <span uid="303" class="token attr-name">type</span><span uid="305" class="token attr-value"><span uid="306" class="token punctuation">=</span><span uid="308" class="token punctuation">"</span>primary<span uid="311" class="token punctuation">"</span></span><span uid="313" class="token punctuation">&gt;</span></span>主要按钮<span uid="316" class="token tag"><span uid="317" class="token tag"><span uid="318" class="token punctuation">&lt;/</span>se-button</span><span uid="321" class="token punctuation">&gt;</span></span>
      <span uid="324" class="token tag"><span uid="325" class="token tag"><span uid="326" class="token punctuation">&lt;</span>se-button</span> <span uid="330" class="token attr-name">type</span><span uid="332" class="token attr-value"><span uid="333" class="token punctuation">=</span><span uid="335" class="token punctuation">"</span>warn<span uid="338" class="token punctuation">"</span></span><span uid="340" class="token punctuation">&gt;</span></span>警告按钮<span uid="343" class="token tag"><span uid="344" class="token tag"><span uid="345" class="token punctuation">&lt;/</span>se-button</span><span uid="348" class="token punctuation">&gt;</span></span>
      <span uid="351" class="token tag"><span uid="352" class="token tag"><span uid="353" class="token punctuation">&lt;</span>se-button</span> <span uid="357" class="token attr-name">type</span><span uid="359" class="token attr-value"><span uid="360" class="token punctuation">=</span><span uid="362" class="token punctuation">"</span>danger<span uid="365" class="token punctuation">"</span></span><span uid="367" class="token punctuation">&gt;</span></span>危险按钮<span uid="370" class="token tag"><span uid="371" class="token tag"><span uid="372" class="token punctuation">&lt;/</span>se-button</span><span uid="375" class="token punctuation">&gt;</span></span>
      </code></pre></div> <h3 uid="379">plain 按钮</h3> <div uid="382" class="vue-demo-block"><div uid="383" class="vue-demo"><button uid="384" class="se-button se-button--default se-button--plain"><!---->朴素按钮</button> <button uid="388" class="se-button se-button--primary se-button--plain"><!---->主要按钮</button> <button uid="392" class="se-button se-button--warn se-button--plain"><!---->警告按钮</button> <button uid="396" class="se-button se-button--danger se-button--plain"><!---->危险按钮</button></div> <div uid="400"></div> <pre uid="402" class="vue-demo-source-code"><code uid="403" class="language-html"><span uid="404" class="token tag"><span uid="405" class="token tag"><span uid="406" class="token punctuation">&lt;</span>se-button</span> <span uid="410" class="token attr-name">plain</span> <span uid="413" class="token attr-name">type</span><span uid="415" class="token attr-value"><span uid="416" class="token punctuation">=</span><span uid="418" class="token punctuation">"</span>default<span uid="421" class="token punctuation">"</span></span><span uid="423" class="token punctuation">&gt;</span></span>朴素按钮<span uid="426" class="token tag"><span uid="427" class="token tag"><span uid="428" class="token punctuation">&lt;/</span>se-button</span><span uid="431" class="token punctuation">&gt;</span></span>
      <span uid="434" class="token tag"><span uid="435" class="token tag"><span uid="436" class="token punctuation">&lt;</span>se-button</span> <span uid="440" class="token attr-name">plain</span> <span uid="443" class="token attr-name">type</span><span uid="445" class="token attr-value"><span uid="446" class="token punctuation">=</span><span uid="448" class="token punctuation">"</span>primary<span uid="451" class="token punctuation">"</span></span><span uid="453" class="token punctuation">&gt;</span></span>主要按钮<span uid="456" class="token tag"><span uid="457" class="token tag"><span uid="458" class="token punctuation">&lt;/</span>se-button</span><span uid="461" class="token punctuation">&gt;</span></span>
      <span uid="464" class="token tag"><span uid="465" class="token tag"><span uid="466" class="token punctuation">&lt;</span>se-button</span> <span uid="470" class="token attr-name">plain</span> <span uid="473" class="token attr-name">type</span><span uid="475" class="token attr-value"><span uid="476" class="token punctuation">=</span><span uid="478" class="token punctuation">"</span>warn<span uid="481" class="token punctuation">"</span></span><span uid="483" class="token punctuation">&gt;</span></span>警告按钮<span uid="486" class="token tag"><span uid="487" class="token tag"><span uid="488" class="token punctuation">&lt;/</span>se-button</span><span uid="491" class="token punctuation">&gt;</span></span>
      <span uid="494" class="token tag"><span uid="495" class="token tag"><span uid="496" class="token punctuation">&lt;</span>se-button</span> <span uid="500" class="token attr-name">plain</span> <span uid="503" class="token attr-name">type</span><span uid="505" class="token attr-value"><span uid="506" class="token punctuation">=</span><span uid="508" class="token punctuation">"</span>danger<span uid="511" class="token punctuation">"</span></span><span uid="513" class="token punctuation">&gt;</span></span>危险按钮<span uid="516" class="token tag"><span uid="517" class="token tag"><span uid="518" class="token punctuation">&lt;/</span>se-button</span><span uid="521" class="token punctuation">&gt;</span></span>
      </code></pre></div> <h2 uid="525">禁用状态</h2> <div uid="528" class="vue-demo-block"><div uid="529" class="vue-demo"><div uid="530"><button uid="531" disabled="disabled" class="se-button se-button--default"><!---->按钮</button> <button uid="535" disabled="disabled" class="se-button se-button--primary"><!---->按钮</button> <button uid="539" disabled="disabled" class="se-button se-button--warn"><!---->按钮</button> <button uid="543" disabled="disabled" class="se-button se-button--danger"><!---->按钮</button></div> <br uid="547"> <div uid="549"><button uid="550" disabled="disabled" class="se-button se-button--default se-button--plain"><!---->朴素按钮</button> <button uid="554" disabled="disabled" class="se-button se-button--primary se-button--plain"><!---->主要按钮</button> <button uid="558" disabled="disabled" class="se-button se-button--warn se-button--plain"><!---->警告按钮</button> <button uid="562" disabled="disabled" class="se-button se-button--danger se-button--plain"><!---->危险按钮</button></div></div> <div uid="566"></div> <pre uid="568" class="vue-demo-source-code"><code uid="569" class="language-html"><span uid="570" class="token tag"><span uid="571" class="token tag"><span uid="572" class="token punctuation">&lt;</span>div</span><span uid="575" class="token punctuation">&gt;</span></span>
        <span uid="578" class="token tag"><span uid="579" class="token tag"><span uid="580" class="token punctuation">&lt;</span>se-button</span> <span uid="584" class="token attr-name">disabled</span> <span uid="587" class="token attr-name">type</span><span uid="589" class="token attr-value"><span uid="590" class="token punctuation">=</span><span uid="592" class="token punctuation">"</span>default<span uid="595" class="token punctuation">"</span></span><span uid="597" class="token punctuation">&gt;</span></span>按钮<span uid="600" class="token tag"><span uid="601" class="token tag"><span uid="602" class="token punctuation">&lt;/</span>se-button</span><span uid="605" class="token punctuation">&gt;</span></span>
        <span uid="608" class="token tag"><span uid="609" class="token tag"><span uid="610" class="token punctuation">&lt;</span>se-button</span> <span uid="614" class="token attr-name">disabled</span> <span uid="617" class="token attr-name">type</span><span uid="619" class="token attr-value"><span uid="620" class="token punctuation">=</span><span uid="622" class="token punctuation">"</span>primary<span uid="625" class="token punctuation">"</span></span><span uid="627" class="token punctuation">&gt;</span></span>按钮<span uid="630" class="token tag"><span uid="631" class="token tag"><span uid="632" class="token punctuation">&lt;/</span>se-button</span><span uid="635" class="token punctuation">&gt;</span></span>
        <span uid="638" class="token tag"><span uid="639" class="token tag"><span uid="640" class="token punctuation">&lt;</span>se-button</span> <span uid="644" class="token attr-name">disabled</span> <span uid="647" class="token attr-name">type</span><span uid="649" class="token attr-value"><span uid="650" class="token punctuation">=</span><span uid="652" class="token punctuation">"</span>warn<span uid="655" class="token punctuation">"</span></span><span uid="657" class="token punctuation">&gt;</span></span>按钮<span uid="660" class="token tag"><span uid="661" class="token tag"><span uid="662" class="token punctuation">&lt;/</span>se-button</span><span uid="665" class="token punctuation">&gt;</span></span>
        <span uid="668" class="token tag"><span uid="669" class="token tag"><span uid="670" class="token punctuation">&lt;</span>se-button</span> <span uid="674" class="token attr-name">disabled</span> <span uid="677" class="token attr-name">type</span><span uid="679" class="token attr-value"><span uid="680" class="token punctuation">=</span><span uid="682" class="token punctuation">"</span>danger<span uid="685" class="token punctuation">"</span></span><span uid="687" class="token punctuation">&gt;</span></span>按钮<span uid="690" class="token tag"><span uid="691" class="token tag"><span uid="692" class="token punctuation">&lt;/</span>se-button</span><span uid="695" class="token punctuation">&gt;</span></span>
      <span uid="698" class="token tag"><span uid="699" class="token tag"><span uid="700" class="token punctuation">&lt;/</span>div</span><span uid="703" class="token punctuation">&gt;</span></span>
      <span uid="706" class="token tag"><span uid="707" class="token tag"><span uid="708" class="token punctuation">&lt;</span>br</span> <span uid="712" class="token punctuation">/&gt;</span></span>
      <span uid="715" class="token tag"><span uid="716" class="token tag"><span uid="717" class="token punctuation">&lt;</span>div</span><span uid="720" class="token punctuation">&gt;</span></span>
        <span uid="723" class="token tag"><span uid="724" class="token tag"><span uid="725" class="token punctuation">&lt;</span>se-button</span> <span uid="729" class="token attr-name">disabled</span> <span uid="732" class="token attr-name">plain</span> <span uid="735" class="token attr-name">type</span><span uid="737" class="token attr-value"><span uid="738" class="token punctuation">=</span><span uid="740" class="token punctuation">"</span>default<span uid="743" class="token punctuation">"</span></span><span uid="745" class="token punctuation">&gt;</span></span>朴素按钮<span uid="748" class="token tag"><span uid="749" class="token tag"><span uid="750" class="token punctuation">&lt;/</span>se-button</span><span uid="753" class="token punctuation">&gt;</span></span>
        <span uid="756" class="token tag"><span uid="757" class="token tag"><span uid="758" class="token punctuation">&lt;</span>se-button</span> <span uid="762" class="token attr-name">disabled</span> <span uid="765" class="token attr-name">plain</span> <span uid="768" class="token attr-name">type</span><span uid="770" class="token attr-value"><span uid="771" class="token punctuation">=</span><span uid="773" class="token punctuation">"</span>primary<span uid="776" class="token punctuation">"</span></span><span uid="778" class="token punctuation">&gt;</span></span>主要按钮<span uid="781" class="token tag"><span uid="782" class="token tag"><span uid="783" class="token punctuation">&lt;/</span>se-button</span><span uid="786" class="token punctuation">&gt;</span></span>
        <span uid="789" class="token tag"><span uid="790" class="token tag"><span uid="791" class="token punctuation">&lt;</span>se-button</span> <span uid="795" class="token attr-name">disabled</span> <span uid="798" class="token attr-name">plain</span> <span uid="801" class="token attr-name">type</span><span uid="803" class="token attr-value"><span uid="804" class="token punctuation">=</span><span uid="806" class="token punctuation">"</span>warn<span uid="809" class="token punctuation">"</span></span><span uid="811" class="token punctuation">&gt;</span></span>警告按钮<span uid="814" class="token tag"><span uid="815" class="token tag"><span uid="816" class="token punctuation">&lt;/</span>se-button</span><span uid="819" class="token punctuation">&gt;</span></span>
        <span uid="822" class="token tag"><span uid="823" class="token tag"><span uid="824" class="token punctuation">&lt;</span>se-button</span> <span uid="828" class="token attr-name">disabled</span> <span uid="831" class="token attr-name">plain</span> <span uid="834" class="token attr-name">type</span><span uid="836" class="token attr-value"><span uid="837" class="token punctuation">=</span><span uid="839" class="token punctuation">"</span>danger<span uid="842" class="token punctuation">"</span></span><span uid="844" class="token punctuation">&gt;</span></span>危险按钮<span uid="847" class="token tag"><span uid="848" class="token tag"><span uid="849" class="token punctuation">&lt;/</span>se-button</span><span uid="852" class="token punctuation">&gt;</span></span>
      <span uid="855" class="token tag"><span uid="856" class="token tag"><span uid="857" class="token punctuation">&lt;/</span>div</span><span uid="860" class="token punctuation">&gt;</span></span>
      </code></pre></div> <h2 uid="864">不同尺寸</h2> <p uid="867">按钮尺寸（<code uid="869">props.size</code>）分为 <code uid="872">default</code> <code uid="875">mini</code> <code uid="878">large</code> 三种，默认为 <code uid="881">default</code>。</p> <div uid="885" class="vue-demo-block"><div uid="886" class="vue-demo"><div uid="887"><button uid="888" class="se-button se-button--default se-button--size-large se-button--plain"><!---->large 按钮</button> <button uid="892" class="se-button se-button--default se-button--plain"><!---->默认按钮</button> <button uid="896" class="se-button se-button--default se-button--size-mini se-button--plain"><!---->mini 按钮</button></div> <br uid="900"> <br uid="902"> <div uid="904"><button uid="905" class="se-button se-button--primary se-button--size-large"><!---->large 按钮</button> <button uid="909" class="se-button se-button--primary"><!---->默认按钮</button> <button uid="913" class="se-button se-button--primary se-button--size-mini"><!---->mini 按钮</button></div></div> <div uid="917"></div> <pre uid="919" class="vue-demo-source-code"><code uid="920" class="language-html"><span uid="921" class="token tag"><span uid="922" class="token tag"><span uid="923" class="token punctuation">&lt;</span>div</span><span uid="926" class="token punctuation">&gt;</span></span>
        <span uid="929" class="token tag"><span uid="930" class="token tag"><span uid="931" class="token punctuation">&lt;</span>se-button</span> <span uid="935" class="token attr-name">plain</span> <span uid="938" class="token attr-name">size</span><span uid="940" class="token attr-value"><span uid="941" class="token punctuation">=</span><span uid="943" class="token punctuation">"</span>large<span uid="946" class="token punctuation">"</span></span><span uid="948" class="token punctuation">&gt;</span></span>large 按钮<span uid="951" class="token tag"><span uid="952" class="token tag"><span uid="953" class="token punctuation">&lt;/</span>se-button</span><span uid="956" class="token punctuation">&gt;</span></span>
        <span uid="959" class="token tag"><span uid="960" class="token tag"><span uid="961" class="token punctuation">&lt;</span>se-button</span> <span uid="965" class="token attr-name">plain</span> <span uid="968" class="token attr-name">size</span><span uid="970" class="token attr-value"><span uid="971" class="token punctuation">=</span><span uid="973" class="token punctuation">"</span>default<span uid="976" class="token punctuation">"</span></span><span uid="978" class="token punctuation">&gt;</span></span>默认按钮<span uid="981" class="token tag"><span uid="982" class="token tag"><span uid="983" class="token punctuation">&lt;/</span>se-button</span><span uid="986" class="token punctuation">&gt;</span></span>
        <span uid="989" class="token tag"><span uid="990" class="token tag"><span uid="991" class="token punctuation">&lt;</span>se-button</span> <span uid="995" class="token attr-name">plain</span> <span uid="998" class="token attr-name">size</span><span uid="1000" class="token attr-value"><span uid="1001" class="token punctuation">=</span><span uid="1003" class="token punctuation">"</span>mini<span uid="1006" class="token punctuation">"</span></span><span uid="1008" class="token punctuation">&gt;</span></span>mini 按钮<span uid="1011" class="token tag"><span uid="1012" class="token tag"><span uid="1013" class="token punctuation">&lt;/</span>se-button</span><span uid="1016" class="token punctuation">&gt;</span></span>
      <span uid="1019" class="token tag"><span uid="1020" class="token tag"><span uid="1021" class="token punctuation">&lt;/</span>div</span><span uid="1024" class="token punctuation">&gt;</span></span>
      <span uid="1027" class="token tag"><span uid="1028" class="token tag"><span uid="1029" class="token punctuation">&lt;</span>br</span><span uid="1032" class="token punctuation">/&gt;</span></span>
      <span uid="1035" class="token tag"><span uid="1036" class="token tag"><span uid="1037" class="token punctuation">&lt;</span>br</span><span uid="1040" class="token punctuation">/&gt;</span></span>
      <span uid="1043" class="token tag"><span uid="1044" class="token tag"><span uid="1045" class="token punctuation">&lt;</span>div</span><span uid="1048" class="token punctuation">&gt;</span></span>
        <span uid="1051" class="token tag"><span uid="1052" class="token tag"><span uid="1053" class="token punctuation">&lt;</span>se-button</span> <span uid="1057" class="token attr-name">type</span><span uid="1059" class="token attr-value"><span uid="1060" class="token punctuation">=</span><span uid="1062" class="token punctuation">"</span>primary<span uid="1065" class="token punctuation">"</span></span> <span uid="1068" class="token attr-name">size</span><span uid="1070" class="token attr-value"><span uid="1071" class="token punctuation">=</span><span uid="1073" class="token punctuation">"</span>large<span uid="1076" class="token punctuation">"</span></span><span uid="1078" class="token punctuation">&gt;</span></span>large 按钮<span uid="1081" class="token tag"><span uid="1082" class="token tag"><span uid="1083" class="token punctuation">&lt;/</span>se-button</span><span uid="1086" class="token punctuation">&gt;</span></span>
        <span uid="1089" class="token tag"><span uid="1090" class="token tag"><span uid="1091" class="token punctuation">&lt;</span>se-button</span> <span uid="1095" class="token attr-name">type</span><span uid="1097" class="token attr-value"><span uid="1098" class="token punctuation">=</span><span uid="1100" class="token punctuation">"</span>primary<span uid="1103" class="token punctuation">"</span></span> <span uid="1106" class="token attr-name">size</span><span uid="1108" class="token attr-value"><span uid="1109" class="token punctuation">=</span><span uid="1111" class="token punctuation">"</span>default<span uid="1114" class="token punctuation">"</span></span><span uid="1116" class="token punctuation">&gt;</span></span>默认按钮<span uid="1119" class="token tag"><span uid="1120" class="token tag"><span uid="1121" class="token punctuation">&lt;/</span>se-button</span><span uid="1124" class="token punctuation">&gt;</span></span>
        <span uid="1127" class="token tag"><span uid="1128" class="token tag"><span uid="1129" class="token punctuation">&lt;</span>se-button</span> <span uid="1133" class="token attr-name">type</span><span uid="1135" class="token attr-value"><span uid="1136" class="token punctuation">=</span><span uid="1138" class="token punctuation">"</span>primary<span uid="1141" class="token punctuation">"</span></span> <span uid="1144" class="token attr-name">size</span><span uid="1146" class="token attr-value"><span uid="1147" class="token punctuation">=</span><span uid="1149" class="token punctuation">"</span>mini<span uid="1152" class="token punctuation">"</span></span><span uid="1154" class="token punctuation">&gt;</span></span>mini 按钮<span uid="1157" class="token tag"><span uid="1158" class="token tag"><span uid="1159" class="token punctuation">&lt;/</span>se-button</span><span uid="1162" class="token punctuation">&gt;</span></span>
      <span uid="1165" class="token tag"><span uid="1166" class="token tag"><span uid="1167" class="token punctuation">&lt;/</span>div</span><span uid="1170" class="token punctuation">&gt;</span></span>
      </code></pre></div> <h2 uid="1174">文字按钮</h2> <div uid="1177" class="vue-demo-block"><div uid="1178" class="vue-demo"><button uid="1179" class="se-button se-button--text"><!---->文字按钮</button> <button uid="1183" disabled="disabled" class="se-button se-button--text"><!---->文字按钮</button></div> <div uid="1187"></div> <pre uid="1189" class="vue-demo-source-code"><code uid="1190" class="language-html"><span uid="1191" class="token tag"><span uid="1192" class="token tag"><span uid="1193" class="token punctuation">&lt;</span>se-button</span> <span uid="1197" class="token attr-name">type</span><span uid="1199" class="token attr-value"><span uid="1200" class="token punctuation">=</span><span uid="1202" class="token punctuation">"</span>text<span uid="1205" class="token punctuation">"</span></span><span uid="1207" class="token punctuation">&gt;</span></span>文字按钮<span uid="1210" class="token tag"><span uid="1211" class="token tag"><span uid="1212" class="token punctuation">&lt;/</span>se-button</span><span uid="1215" class="token punctuation">&gt;</span></span>
      <span uid="1218" class="token tag"><span uid="1219" class="token tag"><span uid="1220" class="token punctuation">&lt;</span>se-button</span> <span uid="1224" class="token attr-name">disabled</span> <span uid="1227" class="token attr-name">type</span><span uid="1229" class="token attr-value"><span uid="1230" class="token punctuation">=</span><span uid="1232" class="token punctuation">"</span>text<span uid="1235" class="token punctuation">"</span></span><span uid="1237" class="token punctuation">&gt;</span></span>文字按钮<span uid="1240" class="token tag"><span uid="1241" class="token tag"><span uid="1242" class="token punctuation">&lt;/</span>se-button</span><span uid="1245" class="token punctuation">&gt;</span></span>
      </code></pre></div> <h2 uid="1249">图标按钮</h2> <p uid="1252">按钮中可以嵌套图标组件，或是通过引入字体图标，都可实现图标按钮。</p> <div uid="1255" class="vue-demo-block"><div uid="1256" data-v-a891b750="" class="vue-demo"><section uid="1257" data-v-a891b750=""><h5 uid="1258" data-v-a891b750="">嵌套图标组件实现图标按钮</h5> <button uid="1261" data-v-a891b750="" class="se-button se-button--primary se-button--size-large"><!----><i uid="1263" data-v-a891b750="" class="se-button__icon"><svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M7 0H5V5H0V7H5V12H7V7H12V5H7V0Z" fill="white"></path></svg></i>新建</button> <button uid="1268" data-v-a891b750="" class="se-button se-button--primary"><!----><i uid="1270" data-v-a891b750="" class="se-button__icon"><svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M7 0H5V5H0V7H5V12H7V7H12V5H7V0Z" fill="white"></path></svg></i>新建</button> <button uid="1275" data-v-a891b750="" class="se-button se-button--primary se-button--size-mini"><!----><i uid="1277" data-v-a891b750="" class="se-button__icon"><svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M7 0H5V5H0V7H5V12H7V7H12V5H7V0Z" fill="white"></path></svg></i>新建</button> <button uid="1282" data-v-a891b750="" class="se-button se-button--default se-button--plain"><!----><i uid="1284" data-v-a891b750="" class="se-button__icon"><svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M7 0H5V5H0V7H5V12H7V7H12V5H7V0Z" fill="white"></path></svg></i>新建</button> <button uid="1289" data-v-a891b750="" class="se-button se-button--text"><!----><i uid="1291" data-v-a891b750="" class="se-button__icon"><svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M7 0H5V5H0V7H5V12H7V7H12V5H7V0Z" fill="white"></path></svg></i>新建</button></section> <section uid="1296" data-v-a891b750=""><h5 uid="1297" data-v-a891b750="">字体图标实现图标按钮</h5> <button uid="1300" data-v-a891b750="" class="se-button se-button--default"><!----><i uid="1302" data-v-a891b750="" class="icon-heart"></i>点赞</button></section></div> <div uid="1305"></div> <pre uid="1307" class="vue-demo-source-code"><code uid="1308" class="language-html"><span uid="1309" class="token tag"><span uid="1310" class="token tag"><span uid="1311" class="token punctuation">&lt;</span>section</span><span uid="1314" class="token punctuation">&gt;</span></span>
        <span uid="1317" class="token tag"><span uid="1318" class="token tag"><span uid="1319" class="token punctuation">&lt;</span>h5</span><span uid="1322" class="token punctuation">&gt;</span></span>嵌套图标组件实现图标按钮<span uid="1325" class="token tag"><span uid="1326" class="token tag"><span uid="1327" class="token punctuation">&lt;/</span>h5</span><span uid="1330" class="token punctuation">&gt;</span></span>
        <span uid="1333" class="token tag"><span uid="1334" class="token tag"><span uid="1335" class="token punctuation">&lt;</span>se-button</span> <span uid="1339" class="token attr-name">type</span><span uid="1341" class="token attr-value"><span uid="1342" class="token punctuation">=</span><span uid="1344" class="token punctuation">"</span>primary<span uid="1347" class="token punctuation">"</span></span> <span uid="1350" class="token attr-name">size</span><span uid="1352" class="token attr-value"><span uid="1353" class="token punctuation">=</span><span uid="1355" class="token punctuation">"</span>large<span uid="1358" class="token punctuation">"</span></span><span uid="1360" class="token punctuation">&gt;</span></span><span uid="1362" class="token tag"><span uid="1363" class="token tag"><span uid="1364" class="token punctuation">&lt;</span>icon-plus</span> <span uid="1368" class="token punctuation">/&gt;</span></span>新建<span uid="1371" class="token tag"><span uid="1372" class="token tag"><span uid="1373" class="token punctuation">&lt;/</span>se-button</span><span uid="1376" class="token punctuation">&gt;</span></span>
        <span uid="1379" class="token tag"><span uid="1380" class="token tag"><span uid="1381" class="token punctuation">&lt;</span>se-button</span> <span uid="1385" class="token attr-name">type</span><span uid="1387" class="token attr-value"><span uid="1388" class="token punctuation">=</span><span uid="1390" class="token punctuation">"</span>primary<span uid="1393" class="token punctuation">"</span></span><span uid="1395" class="token punctuation">&gt;</span></span><span uid="1397" class="token tag"><span uid="1398" class="token tag"><span uid="1399" class="token punctuation">&lt;</span>icon-plus</span> <span uid="1403" class="token punctuation">/&gt;</span></span>新建<span uid="1406" class="token tag"><span uid="1407" class="token tag"><span uid="1408" class="token punctuation">&lt;/</span>se-button</span><span uid="1411" class="token punctuation">&gt;</span></span>
        <span uid="1414" class="token tag"><span uid="1415" class="token tag"><span uid="1416" class="token punctuation">&lt;</span>se-button</span> <span uid="1420" class="token attr-name">type</span><span uid="1422" class="token attr-value"><span uid="1423" class="token punctuation">=</span><span uid="1425" class="token punctuation">"</span>primary<span uid="1428" class="token punctuation">"</span></span> <span uid="1431" class="token attr-name">size</span><span uid="1433" class="token attr-value"><span uid="1434" class="token punctuation">=</span><span uid="1436" class="token punctuation">"</span>mini<span uid="1439" class="token punctuation">"</span></span><span uid="1441" class="token punctuation">&gt;</span></span><span uid="1443" class="token tag"><span uid="1444" class="token tag"><span uid="1445" class="token punctuation">&lt;</span>icon-plus</span> <span uid="1449" class="token punctuation">/&gt;</span></span>新建<span uid="1452" class="token tag"><span uid="1453" class="token tag"><span uid="1454" class="token punctuation">&lt;/</span>se-button</span><span uid="1457" class="token punctuation">&gt;</span></span>
        <span uid="1460" class="token tag"><span uid="1461" class="token tag"><span uid="1462" class="token punctuation">&lt;</span>se-button</span> <span uid="1466" class="token attr-name">type</span><span uid="1468" class="token attr-value"><span uid="1469" class="token punctuation">=</span><span uid="1471" class="token punctuation">"</span>default<span uid="1474" class="token punctuation">"</span></span> <span uid="1477" class="token attr-name">plain</span><span uid="1479" class="token punctuation">&gt;</span></span><span uid="1481" class="token tag"><span uid="1482" class="token tag"><span uid="1483" class="token punctuation">&lt;</span>icon-plus</span> <span uid="1487" class="token punctuation">/&gt;</span></span>新建<span uid="1490" class="token tag"><span uid="1491" class="token tag"><span uid="1492" class="token punctuation">&lt;/</span>se-button</span><span uid="1495" class="token punctuation">&gt;</span></span>
        <span uid="1498" class="token tag"><span uid="1499" class="token tag"><span uid="1500" class="token punctuation">&lt;</span>se-button</span> <span uid="1504" class="token attr-name">type</span><span uid="1506" class="token attr-value"><span uid="1507" class="token punctuation">=</span><span uid="1509" class="token punctuation">"</span>text<span uid="1512" class="token punctuation">"</span></span><span uid="1514" class="token punctuation">&gt;</span></span><span uid="1516" class="token tag"><span uid="1517" class="token tag"><span uid="1518" class="token punctuation">&lt;</span>icon-plus</span> <span uid="1522" class="token punctuation">/&gt;</span></span>新建<span uid="1525" class="token tag"><span uid="1526" class="token tag"><span uid="1527" class="token punctuation">&lt;/</span>se-button</span><span uid="1530" class="token punctuation">&gt;</span></span>
      <span uid="1533" class="token tag"><span uid="1534" class="token tag"><span uid="1535" class="token punctuation">&lt;/</span>section</span><span uid="1538" class="token punctuation">&gt;</span></span>
      
      <span uid="1541" class="token tag"><span uid="1542" class="token tag"><span uid="1543" class="token punctuation">&lt;</span>section</span><span uid="1546" class="token punctuation">&gt;</span></span>
        <span uid="1549" class="token tag"><span uid="1550" class="token tag"><span uid="1551" class="token punctuation">&lt;</span>h5</span><span uid="1554" class="token punctuation">&gt;</span></span>字体图标实现图标按钮<span uid="1557" class="token tag"><span uid="1558" class="token tag"><span uid="1559" class="token punctuation">&lt;/</span>h5</span><span uid="1562" class="token punctuation">&gt;</span></span>
        <span uid="1565" class="token tag"><span uid="1566" class="token tag"><span uid="1567" class="token punctuation">&lt;</span>se-button</span><span uid="1570" class="token punctuation">&gt;</span></span><span uid="1572" class="token tag"><span uid="1573" class="token tag"><span uid="1574" class="token punctuation">&lt;</span>i</span> <span uid="1578" class="token attr-name">class</span><span uid="1580" class="token attr-value"><span uid="1581" class="token punctuation">=</span><span uid="1583" class="token punctuation">"</span>icon-heart<span uid="1586" class="token punctuation">"</span></span><span uid="1588" class="token punctuation">&gt;</span></span><span uid="1590" class="token tag"><span uid="1591" class="token tag"><span uid="1592" class="token punctuation">&lt;/</span>i</span><span uid="1595" class="token punctuation">&gt;</span></span>点赞<span uid="1598" class="token tag"><span uid="1599" class="token tag"><span uid="1600" class="token punctuation">&lt;/</span>se-button</span><span uid="1603" class="token punctuation">&gt;</span></span>
      <span uid="1606" class="token tag"><span uid="1607" class="token tag"><span uid="1608" class="token punctuation">&lt;/</span>section</span><span uid="1611" class="token punctuation">&gt;</span></span>
      
      <span uid="1614" class="token tag"><span uid="1615" class="token tag"><span uid="1616" class="token punctuation">&lt;</span>script</span><span uid="1619" class="token punctuation">&gt;</span></span><span uid="1621" class="token script"><span uid="1622" class="token language-javascript">
      <span uid="1624" class="token keyword module">export</span> <span uid="1627" class="token keyword module">default</span> <span uid="1630" class="token punctuation">{</span>
        components<span uid="1633" class="token punctuation">:</span> <span uid="1636" class="token punctuation">{</span>
          <span uid="1639" class="token string">'icon-plus'</span><span uid="1641" class="token punctuation">:</span> <span uid="1644" class="token punctuation">{</span>
            <span uid="1647" class="token function">render</span><span uid="1649" class="token punctuation">(</span><span uid="1651" class="token parameter">h</span><span uid="1653" class="token punctuation">)</span> <span uid="1656" class="token punctuation">{</span>
              <span uid="1659" class="token keyword">return</span> <span uid="1662" class="token function">h</span><span uid="1664" class="token punctuation">(</span><span uid="1666" class="token string">'i'</span><span uid="1668" class="token punctuation">,</span>
                <span uid="1671" class="token punctuation">{</span>
                  <span uid="1674" class="token keyword">class</span><span uid="1676" class="token punctuation">:</span><span uid="1678" class="token string">"se-button__icon"</span>
                <span uid="1681" class="token punctuation">}</span><span uid="1683" class="token punctuation">,</span>
                <span uid="1686" class="token punctuation">[</span><span uid="1688" class="token function">h</span><span uid="1690" class="token punctuation">(</span><span uid="1692" class="token string">'svg'</span><span uid="1694" class="token punctuation">,</span>
                  <span uid="1697" class="token punctuation">{</span>
                    attrs<span uid="1700" class="token punctuation">:</span> <span uid="1703" class="token punctuation">{</span>
                      width<span uid="1706" class="token punctuation">:</span> <span uid="1709" class="token string">"12"</span><span uid="1711" class="token punctuation">,</span>
                      height<span uid="1714" class="token punctuation">:</span> <span uid="1717" class="token string">"12"</span><span uid="1719" class="token punctuation">,</span>
                      viewBox<span uid="1722" class="token punctuation">:</span> <span uid="1725" class="token string">"0 0 12 12"</span><span uid="1727" class="token punctuation">,</span>
                      fill<span uid="1730" class="token punctuation">:</span> <span uid="1733" class="token string">"none"</span><span uid="1735" class="token punctuation">,</span>
                      xmlns<span uid="1738" class="token punctuation">:</span> <span uid="1741" class="token string">"http://www.w3.org/2000/svg"</span>
                    <span uid="1744" class="token punctuation">}</span>
                  <span uid="1747" class="token punctuation">}</span><span uid="1749" class="token punctuation">,</span>
                  <span uid="1752" class="token punctuation">[</span><span uid="1754" class="token function">h</span><span uid="1756" class="token punctuation">(</span><span uid="1758" class="token string">'path'</span><span uid="1760" class="token punctuation">,</span>
                    <span uid="1763" class="token punctuation">{</span>
                      attrs<span uid="1766" class="token punctuation">:</span> <span uid="1769" class="token punctuation">{</span>
                        <span uid="1772" class="token string">'fill-rule'</span><span uid="1774" class="token punctuation">:</span> <span uid="1777" class="token string">"evenodd"</span><span uid="1779" class="token punctuation">,</span>
                        <span uid="1782" class="token string">'clip-rule'</span><span uid="1784" class="token punctuation">:</span> <span uid="1787" class="token string">"evenodd"</span><span uid="1789" class="token punctuation">,</span>
                        <span uid="1792" class="token string">'d'</span><span uid="1794" class="token punctuation">:</span> <span uid="1797" class="token string">"M7 0H5V5H0V7H5V12H7V7H12V5H7V0Z"</span><span uid="1799" class="token punctuation">,</span>
                        <span uid="1802" class="token string">'fill'</span><span uid="1804" class="token punctuation">:</span> <span uid="1807" class="token string">"white"</span>
                      <span uid="1810" class="token punctuation">}</span>
                    <span uid="1813" class="token punctuation">}</span>
                  <span uid="1816" class="token punctuation">)</span><span uid="1818" class="token punctuation">]</span>          
                <span uid="1821" class="token punctuation">)</span><span uid="1823" class="token punctuation">]</span>
              <span uid="1826" class="token punctuation">)</span>
            <span uid="1829" class="token punctuation">}</span>
          <span uid="1832" class="token punctuation">}</span>
        <span uid="1835" class="token punctuation">}</span>
      <span uid="1838" class="token punctuation">}</span>
      </span></span><span uid="1841" class="token tag"><span uid="1842" class="token tag"><span uid="1843" class="token punctuation">&lt;/</span>script</span><span uid="1846" class="token punctuation">&gt;</span></span>
      <span uid="1849" class="token tag"><span uid="1850" class="token tag"><span uid="1851" class="token punctuation">&lt;</span>style</span> <span uid="1855" class="token attr-name">scoped</span><span uid="1857" class="token punctuation">&gt;</span></span><span uid="1859" class="token style"><span uid="1860" class="token language-css">
      <span uid="1862" class="token selector">section + section</span> <span uid="1865" class="token punctuation">{</span>
        <span uid="1868" class="token property">margin-top</span><span uid="1870" class="token punctuation">:</span> <span uid="1873" class="token number">40</span><span uid="1875" class="token unit">px</span><span uid="1877" class="token punctuation">;</span>
      <span uid="1880" class="token punctuation">}</span>
      <span uid="1883" class="token selector"><span uid="1884" class="token class">.icon-heart</span></span> <span uid="1887" class="token punctuation">{</span>
        <span uid="1890" class="token property">display</span><span uid="1892" class="token punctuation">:</span> inline-block<span uid="1895" class="token punctuation">;</span>
        <span uid="1898" class="token property">font-style</span><span uid="1900" class="token punctuation">:</span> normal<span uid="1903" class="token punctuation">;</span>
      <span uid="1906" class="token punctuation">}</span>
      <span uid="1909" class="token selector"><span uid="1910" class="token class">.icon-heart</span><span uid="1912" class="token pseudo-element">::before</span></span> <span uid="1915" class="token punctuation">{</span>
        <span uid="1918" class="token property">content</span><span uid="1920" class="token punctuation">:</span> <span uid="1923" class="token string"></span><span uid="1925" class="token punctuation">;</span>
      <span uid="1928" class="token punctuation">}</span>
      </span></span><span uid="1931" class="token tag"><span uid="1932" class="token tag"><span uid="1933" class="token punctuation">&lt;/</span>style</span><span uid="1936" class="token punctuation">&gt;</span></span>
      </code></pre></div> <h2 uid="1940">block 按钮</h2> <div uid="1943" class="vue-demo-block"><div uid="1944" data-v-248a69a6="" class="vue-demo"><div uid="1945" data-v-248a69a6="" class="block-buttons"><button uid="1946" data-v-248a69a6="" class="se-button se-button--default se-button--block"><!---->默认按钮</button> <button uid="1950" data-v-248a69a6="" class="se-button se-button--primary se-button--block"><!---->主要按钮</button> <button uid="1954" data-v-248a69a6="" class="se-button se-button--warn se-button--block"><!---->警告按钮</button> <button uid="1958" data-v-248a69a6="" class="se-button se-button--danger se-button--block"><!---->危险按钮</button></div></div> <div uid="1962"></div> <pre uid="1964" class="vue-demo-source-code"><code uid="1965" class="language-html"><span uid="1966" class="token tag"><span uid="1967" class="token tag"><span uid="1968" class="token punctuation">&lt;</span>div</span> <span uid="1972" class="token attr-name">class</span><span uid="1974" class="token attr-value"><span uid="1975" class="token punctuation">=</span><span uid="1977" class="token punctuation">"</span>block-buttons<span uid="1980" class="token punctuation">"</span></span><span uid="1982" class="token punctuation">&gt;</span></span>
        <span uid="1985" class="token tag"><span uid="1986" class="token tag"><span uid="1987" class="token punctuation">&lt;</span>se-button</span> <span uid="1991" class="token attr-name">block</span> <span uid="1994" class="token attr-name">type</span><span uid="1996" class="token attr-value"><span uid="1997" class="token punctuation">=</span><span uid="1999" class="token punctuation">"</span>default<span uid="2002" class="token punctuation">"</span></span><span uid="2004" class="token punctuation">&gt;</span></span>默认按钮<span uid="2007" class="token tag"><span uid="2008" class="token tag"><span uid="2009" class="token punctuation">&lt;/</span>se-button</span><span uid="2012" class="token punctuation">&gt;</span></span>
        <span uid="2015" class="token tag"><span uid="2016" class="token tag"><span uid="2017" class="token punctuation">&lt;</span>se-button</span> <span uid="2021" class="token attr-name">block</span> <span uid="2024" class="token attr-name">type</span><span uid="2026" class="token attr-value"><span uid="2027" class="token punctuation">=</span><span uid="2029" class="token punctuation">"</span>primary<span uid="2032" class="token punctuation">"</span></span><span uid="2034" class="token punctuation">&gt;</span></span>主要按钮<span uid="2037" class="token tag"><span uid="2038" class="token tag"><span uid="2039" class="token punctuation">&lt;/</span>se-button</span><span uid="2042" class="token punctuation">&gt;</span></span>
        <span uid="2045" class="token tag"><span uid="2046" class="token tag"><span uid="2047" class="token punctuation">&lt;</span>se-button</span> <span uid="2051" class="token attr-name">block</span> <span uid="2054" class="token attr-name">type</span><span uid="2056" class="token attr-value"><span uid="2057" class="token punctuation">=</span><span uid="2059" class="token punctuation">"</span>warn<span uid="2062" class="token punctuation">"</span></span><span uid="2064" class="token punctuation">&gt;</span></span>警告按钮<span uid="2067" class="token tag"><span uid="2068" class="token tag"><span uid="2069" class="token punctuation">&lt;/</span>se-button</span><span uid="2072" class="token punctuation">&gt;</span></span>
        <span uid="2075" class="token tag"><span uid="2076" class="token tag"><span uid="2077" class="token punctuation">&lt;</span>se-button</span> <span uid="2081" class="token attr-name">block</span> <span uid="2084" class="token attr-name">type</span><span uid="2086" class="token attr-value"><span uid="2087" class="token punctuation">=</span><span uid="2089" class="token punctuation">"</span>danger<span uid="2092" class="token punctuation">"</span></span><span uid="2094" class="token punctuation">&gt;</span></span>危险按钮<span uid="2097" class="token tag"><span uid="2098" class="token tag"><span uid="2099" class="token punctuation">&lt;/</span>se-button</span><span uid="2102" class="token punctuation">&gt;</span></span>
      <span uid="2105" class="token tag"><span uid="2106" class="token tag"><span uid="2107" class="token punctuation">&lt;/</span>div</span><span uid="2110" class="token punctuation">&gt;</span></span>
      
      <span uid="2113" class="token tag"><span uid="2114" class="token tag"><span uid="2115" class="token punctuation">&lt;</span>style</span><span uid="2118" class="token punctuation">&gt;</span></span><span uid="2120" class="token style"><span uid="2121" class="token language-css">
        <span uid="2123" class="token selector"><span uid="2124" class="token class">.block-buttons</span> &gt; <span uid="2127" class="token class">.se-button</span> + <span uid="2130" class="token class">.se-button</span></span> <span uid="2133" class="token punctuation">{</span>
          <span uid="2136" class="token property">margin</span><span uid="2138" class="token punctuation">:</span> <span uid="2141" class="token number">15</span><span uid="2143" class="token unit">px</span> <span uid="2146" class="token number">0</span><span uid="2148" class="token punctuation">;</span>
        <span uid="2151" class="token punctuation">}</span>
      </span></span><span uid="2154" class="token tag"><span uid="2155" class="token tag"><span uid="2156" class="token punctuation">&lt;/</span>style</span><span uid="2159" class="token punctuation">&gt;</span></span>
      </code></pre></div> <h2 uid="2163">加载中</h2> <p uid="2166">点击按钮后进行数据加载操作，在按钮上显示加载状态。</p> <div uid="2169" class="vue-demo-block"><div uid="2170" data-v-13e904da="" class="vue-demo"><div uid="2171" data-v-13e904da="" class="btn-group"><button uid="2172" data-v-13e904da="" disabled="disabled" class="se-button se-button--primary"><i uid="2173" class="se-button__icon se-icon__loading">
        <span uid="2607" class="token tag"><span uid="2608" class="token tag"><span uid="2609" class="token punctuation">&lt;</span>se-button</span> <span uid="2613" class="token attr-name">type</span><span uid="2615" class="token attr-value"><span uid="2616" class="token punctuation">=</span><span uid="2618" class="token punctuation">"</span>primary<span uid="2621" class="token punctuation">"</span></span> <span uid="2624" class="token attr-name">loading</span><span uid="2626" class="token punctuation">&gt;</span></span>加载中<span uid="2629" class="token tag"><span uid="2630" class="token tag"><span uid="2631" class="token punctuation">&lt;/</span>se-button</span><span uid="2634" class="token punctuation">&gt;</span></span>
        <span uid="2637" class="token tag"><span uid="2638" class="token tag"><span uid="2639" class="token punctuation">&lt;</span>se-button</span> <span uid="2643" class="token attr-name">type</span><span uid="2645" class="token attr-value"><span uid="2646" class="token punctuation">=</span><span uid="2648" class="token punctuation">"</span>default<span uid="2651" class="token punctuation">"</span></span> <span uid="2654" class="token attr-name">loading</span><span uid="2656" class="token punctuation">&gt;</span></span>加载中<span uid="2659" class="token tag"><span uid="2660" class="token tag"><span uid="2661" class="token punctuation">&lt;/</span>se-button</span><span uid="2664" class="token punctuation">&gt;</span></span>
        <span uid="2667" class="token tag"><span uid="2668" class="token tag"><span uid="2669" class="token punctuation">&lt;</span>se-button</span> <span uid="2673" class="token attr-name">type</span><span uid="2675" class="token attr-value"><span uid="2676" class="token punctuation">=</span><span uid="2678" class="token punctuation">"</span>text<span uid="2681" class="token punctuation">"</span></span> <span uid="2684" class="token attr-name">loading</span><span uid="2686" class="token punctuation">&gt;</span></span>加载中<span uid="2689" class="token tag"><span uid="2690" class="token tag"><span uid="2691" class="token punctuation">&lt;/</span>se-button</span><span uid="2694" class="token punctuation">&gt;</span></span>
      <span uid="2697" class="token tag"><span uid="2698" class="token tag"><span uid="2699" class="token punctuation">&lt;/</span>div</span><span uid="2702" class="token punctuation">&gt;</span></span>
      
      <span uid="2705" class="token tag"><span uid="2706" class="token tag"><span uid="2707" class="token punctuation">&lt;</span>div</span> <span uid="2711" class="token attr-name">class</span><span uid="2713" class="token attr-value"><span uid="2714" class="token punctuation">=</span><span uid="2716" class="token punctuation">"</span>btn-group<span uid="2719" class="token punctuation">"</span></span><span uid="2721" class="token punctuation">&gt;</span></span>
        <span uid="2724" class="token tag"><span uid="2725" class="token tag"><span uid="2726" class="token punctuation">&lt;</span>se-button</span> <span uid="2730" class="token attr-name">type</span><span uid="2732" class="token attr-value"><span uid="2733" class="token punctuation">=</span><span uid="2735" class="token punctuation">"</span>primary<span uid="2738" class="token punctuation">"</span></span> <span uid="2741" class="token attr-name">size</span><span uid="2743" class="token attr-value"><span uid="2744" class="token punctuation">=</span><span uid="2746" class="token punctuation">"</span>mini<span uid="2749" class="token punctuation">"</span></span> <span uid="2752" class="token attr-name">loading</span><span uid="2754" class="token punctuation">&gt;</span></span>加载中<span uid="2757" class="token tag"><span uid="2758" class="token tag"><span uid="2759" class="token punctuation">&lt;/</span>se-button</span><span uid="2762" class="token punctuation">&gt;</span></span>
        <span uid="2765" class="token tag"><span uid="2766" class="token tag"><span uid="2767" class="token punctuation">&lt;</span>se-button</span> <span uid="2771" class="token attr-name">type</span><span uid="2773" class="token attr-value"><span uid="2774" class="token punctuation">=</span><span uid="2776" class="token punctuation">"</span>default<span uid="2779" class="token punctuation">"</span></span> <span uid="2782" class="token attr-name">size</span><span uid="2784" class="token attr-value"><span uid="2785" class="token punctuation">=</span><span uid="2787" class="token punctuation">"</span>mini<span uid="2790" class="token punctuation">"</span></span> <span uid="2793" class="token attr-name">loading</span><span uid="2795" class="token punctuation">&gt;</span></span>加载中<span uid="2798" class="token tag"><span uid="2799" class="token tag"><span uid="2800" class="token punctuation">&lt;/</span>se-button</span><span uid="2803" class="token punctuation">&gt;</span></span>
        <span uid="2806" class="token tag"><span uid="2807" class="token tag"><span uid="2808" class="token punctuation">&lt;</span>se-button</span> <span uid="2812" class="token attr-name">type</span><span uid="2814" class="token attr-value"><span uid="2815" class="token punctuation">=</span><span uid="2817" class="token punctuation">"</span>text<span uid="2820" class="token punctuation">"</span></span> <span uid="2823" class="token attr-name">size</span><span uid="2825" class="token attr-value"><span uid="2826" class="token punctuation">=</span><span uid="2828" class="token punctuation">"</span>mini<span uid="2831" class="token punctuation">"</span></span> <span uid="2834" class="token attr-name">loading</span><span uid="2836" class="token punctuation">&gt;</span></span>加载中<span uid="2839" class="token tag"><span uid="2840" class="token tag"><span uid="2841" class="token punctuation">&lt;/</span>se-button</span><span uid="2844" class="token punctuation">&gt;</span></span>
      <span uid="2847" class="token tag"><span uid="2848" class="token tag"><span uid="2849" class="token punctuation">&lt;/</span>div</span><span uid="2852" class="token punctuation">&gt;</span></span>
      
      <span uid="2855" class="token tag"><span uid="2856" class="token tag"><span uid="2857" class="token punctuation">&lt;</span>div</span> <span uid="2861" class="token attr-name">class</span><span uid="2863" class="token attr-value"><span uid="2864" class="token punctuation">=</span><span uid="2866" class="token punctuation">"</span>btn-group<span uid="2869" class="token punctuation">"</span></span><span uid="2871" class="token punctuation">&gt;</span></span>
        <span uid="2874" class="token tag"><span uid="2875" class="token tag"><span uid="2876" class="token punctuation">&lt;</span>se-button</span> <span uid="2880" class="token attr-name">type</span><span uid="2882" class="token attr-value"><span uid="2883" class="token punctuation">=</span><span uid="2885" class="token punctuation">"</span>primary<span uid="2888" class="token punctuation">"</span></span> <span uid="2891" class="token attr-name">size</span><span uid="2893" class="token attr-value"><span uid="2894" class="token punctuation">=</span><span uid="2896" class="token punctuation">"</span>large<span uid="2899" class="token punctuation">"</span></span> <span uid="2902" class="token attr-name">loading</span><span uid="2904" class="token punctuation">&gt;</span></span>加载中<span uid="2907" class="token tag"><span uid="2908" class="token tag"><span uid="2909" class="token punctuation">&lt;/</span>se-button</span><span uid="2912" class="token punctuation">&gt;</span></span>
        <span uid="2915" class="token tag"><span uid="2916" class="token tag"><span uid="2917" class="token punctuation">&lt;</span>se-button</span> <span uid="2921" class="token attr-name">type</span><span uid="2923" class="token attr-value"><span uid="2924" class="token punctuation">=</span><span uid="2926" class="token punctuation">"</span>default<span uid="2929" class="token punctuation">"</span></span> <span uid="2932" class="token attr-name">size</span><span uid="2934" class="token attr-value"><span uid="2935" class="token punctuation">=</span><span uid="2937" class="token punctuation">"</span>large<span uid="2940" class="token punctuation">"</span></span> <span uid="2943" class="token attr-name">loading</span><span uid="2945" class="token punctuation">&gt;</span></span>加载中<span uid="2948" class="token tag"><span uid="2949" class="token tag"><span uid="2950" class="token punctuation">&lt;/</span>se-button</span><span uid="2953" class="token punctuation">&gt;</span></span>
        <span uid="2956" class="token tag"><span uid="2957" class="token tag"><span uid="2958" class="token punctuation">&lt;</span>se-button</span> <span uid="2962" class="token attr-name">type</span><span uid="2964" class="token attr-value"><span uid="2965" class="token punctuation">=</span><span uid="2967" class="token punctuation">"</span>text<span uid="2970" class="token punctuation">"</span></span> <span uid="2973" class="token attr-name">size</span><span uid="2975" class="token attr-value"><span uid="2976" class="token punctuation">=</span><span uid="2978" class="token punctuation">"</span>large<span uid="2981" class="token punctuation">"</span></span> <span uid="2984" class="token attr-name">loading</span><span uid="2986" class="token punctuation">&gt;</span></span>加载中<span uid="2989" class="token tag"><span uid="2990" class="token tag"><span uid="2991" class="token punctuation">&lt;/</span>se-button</span><span uid="2994" class="token punctuation">&gt;</span></span>
      <span uid="2997" class="token tag"><span uid="2998" class="token tag"><span uid="2999" class="token punctuation">&lt;/</span>div</span><span uid="3002" class="token punctuation">&gt;</span></span>
      
      <span uid="3005" class="token tag"><span uid="3006" class="token tag"><span uid="3007" class="token punctuation">&lt;</span>se-button</span> <span uid="3011" class="token attr-name">type</span><span uid="3013" class="token attr-value"><span uid="3014" class="token punctuation">=</span><span uid="3016" class="token punctuation">"</span>primary<span uid="3019" class="token punctuation">"</span></span> <span uid="3022" class="token attr-name">block</span> <span uid="3025" class="token attr-name">loading</span><span uid="3027" class="token punctuation">&gt;</span></span>加载中<span uid="3030" class="token tag"><span uid="3031" class="token tag"><span uid="3032" class="token punctuation">&lt;/</span>se-button</span><span uid="3035" class="token punctuation">&gt;</span></span>
      
      <span uid="3038" class="token tag"><span uid="3039" class="token tag"><span uid="3040" class="token punctuation">&lt;</span>style</span> <span uid="3044" class="token attr-name">scoped</span><span uid="3046" class="token punctuation">&gt;</span></span><span uid="3048" class="token style"><span uid="3049" class="token language-css">
      <span uid="3051" class="token selector"><span uid="3052" class="token class">.btn-group</span></span> <span uid="3055" class="token punctuation">{</span>
        <span uid="3058" class="token property">margin-bottom</span><span uid="3060" class="token punctuation">:</span> <span uid="3063" class="token number">20</span><span uid="3065" class="token unit">px</span>
      <span uid="3068" class="token punctuation">}</span>
      </span></span><span uid="3071" class="token tag"><span uid="3072" class="token tag"><span uid="3073" class="token punctuation">&lt;/</span>style</span><span uid="3076" class="token punctuation">&gt;</span></span>
      </code></pre></div> <h2 uid="3080">设置 <code uid="3082">&lt;button&gt;</code> 原生 <code uid="3085">type</code> 属性</h2> <p uid="3089">通过 <code uid="3091">form-type</code> 属性可以设置 <code uid="3094">&lt;button&gt;</code> 原生的 type 属性。可选值: <code uid="3097">submit</code> 和 <code uid="3100">reset</code>。</p> <div uid="3104" class="vue-demo-block"><div uid="3105" data-v-5e002d8f="" class="vue-demo"><form uid="3106" data-v-5e002d8f=""><input uid="3107" data-v-5e002d8f="" name="message"> <button uid="3109" data-v-5e002d8f="" type="reset" class="se-button se-button--default"><!---->重置</button> <button uid="3113" data-v-5e002d8f="" type="submit" class="se-button se-button--primary"><!---->
          提交
        </button></form></div> <div uid="3117"></div> <pre uid="3119" class="vue-demo-source-code"><code uid="3120" class="language-html"><span uid="3121" class="token tag"><span uid="3122" class="token tag"><span uid="3123" class="token punctuation">&lt;</span>form</span><span uid="3126" class="token punctuation">&gt;</span></span>
        <span uid="3129" class="token tag"><span uid="3130" class="token tag"><span uid="3131" class="token punctuation">&lt;</span>input</span> <span uid="3135" class="token attr-name">name</span><span uid="3137" class="token attr-value"><span uid="3138" class="token punctuation">=</span><span uid="3140" class="token punctuation">"</span>message<span uid="3143" class="token punctuation">"</span></span> <span uid="3146" class="token attr-name">v-model</span><span uid="3148" class="token attr-value"><span uid="3149" class="token punctuation">=</span><span uid="3151" class="token punctuation">"</span>msg<span uid="3154" class="token punctuation">"</span></span> <span uid="3157" class="token punctuation">/&gt;</span></span>
        <span uid="3160" class="token tag"><span uid="3161" class="token tag"><span uid="3162" class="token punctuation">&lt;</span>se-button</span> <span uid="3166" class="token attr-name">form-type</span><span uid="3168" class="token attr-value"><span uid="3169" class="token punctuation">=</span><span uid="3171" class="token punctuation">"</span>reset<span uid="3174" class="token punctuation">"</span></span> <span uid="3177" class="token attr-name">type</span><span uid="3179" class="token attr-value"><span uid="3180" class="token punctuation">=</span><span uid="3182" class="token punctuation">"</span>default<span uid="3185" class="token punctuation">"</span></span><span uid="3187" class="token punctuation">&gt;</span></span>重置<span uid="3190" class="token tag"><span uid="3191" class="token tag"><span uid="3192" class="token punctuation">&lt;/</span>se-button</span><span uid="3195" class="token punctuation">&gt;</span></span>
        <span uid="3198" class="token tag"><span uid="3199" class="token tag"><span uid="3200" class="token punctuation">&lt;</span>se-button</span> <span uid="3204" class="token attr-name">form-type</span><span uid="3206" class="token attr-value"><span uid="3207" class="token punctuation">=</span><span uid="3209" class="token punctuation">"</span>submit<span uid="3212" class="token punctuation">"</span></span> <span uid="3215" class="token attr-name">type</span><span uid="3217" class="token attr-value"><span uid="3218" class="token punctuation">=</span><span uid="3220" class="token punctuation">"</span>primary<span uid="3223" class="token punctuation">"</span></span> <span uid="3226" class="token attr-name">@click.native.prevent</span><span uid="3228" class="token attr-value"><span uid="3229" class="token punctuation">=</span><span uid="3231" class="token punctuation">"</span>onSubmit<span uid="3234" class="token punctuation">"</span></span><span uid="3236" class="token punctuation">&gt;</span></span>
          提交
        <span uid="3239" class="token tag"><span uid="3240" class="token tag"><span uid="3241" class="token punctuation">&lt;/</span>se-button</span><span uid="3244" class="token punctuation">&gt;</span></span>
      <span uid="3247" class="token tag"><span uid="3248" class="token tag"><span uid="3249" class="token punctuation">&lt;/</span>form</span><span uid="3252" class="token punctuation">&gt;</span></span>
      
      <span uid="3255" class="token tag"><span uid="3256" class="token tag"><span uid="3257" class="token punctuation">&lt;</span>script</span><span uid="3260" class="token punctuation">&gt;</span></span><span uid="3262" class="token script"><span uid="3263" class="token language-javascript">
        <span uid="3265" class="token keyword module">export</span> <span uid="3268" class="token keyword module">default</span> <span uid="3271" class="token punctuation">{</span>
          <span uid="3274" class="token function">data</span><span uid="3276" class="token punctuation">(</span><span uid="3278" class="token punctuation">)</span> <span uid="3281" class="token punctuation">{</span>
            <span uid="3284" class="token keyword">return</span> <span uid="3287" class="token punctuation">{</span> msg<span uid="3290" class="token punctuation">:</span> <span uid="3293" class="token string">'Hello World'</span> <span uid="3296" class="token punctuation">}</span>
          <span uid="3299" class="token punctuation">}</span><span uid="3301" class="token punctuation">,</span>
          methods<span uid="3304" class="token punctuation">:</span> <span uid="3307" class="token punctuation">{</span>
            <span uid="3310" class="token function">onSubmit</span><span uid="3312" class="token punctuation">(</span><span uid="3314" class="token punctuation">)</span> <span uid="3317" class="token punctuation">{</span>
              <span uid="3320" class="token console class-name">console</span><span uid="3322" class="token punctuation">.</span><span uid="3324" class="token method function property-access">log</span><span uid="3326" class="token punctuation">(</span><span uid="3328" class="token string">'提交成功！'</span><span uid="3330" class="token punctuation">)</span>
            <span uid="3333" class="token punctuation">}</span>
          <span uid="3336" class="token punctuation">}</span>
        <span uid="3339" class="token punctuation">}</span>
      </span></span><span uid="3342" class="token tag"><span uid="3343" class="token tag"><span uid="3344" class="token punctuation">&lt;/</span>script</span><span uid="3347" class="token punctuation">&gt;</span></span>
      
      <span uid="3350" class="token tag"><span uid="3351" class="token tag"><span uid="3352" class="token punctuation">&lt;</span>style</span><span uid="3355" class="token punctuation">&gt;</span></span><span uid="3357" class="token style"><span uid="3358" class="token language-css">
        <span uid="3360" class="token selector"><span uid="3361" class="token class">.se-button</span></span> <span uid="3364" class="token punctuation">{</span>
          <span uid="3367" class="token property">margin-left</span><span uid="3369" class="token punctuation">:</span> <span uid="3372" class="token number">10</span><span uid="3374" class="token unit">px</span><span uid="3376" class="token punctuation">;</span>
        <span uid="3379" class="token punctuation">}</span>
      </span></span><span uid="3382" class="token tag"><span uid="3383" class="token tag"><span uid="3384" class="token punctuation">&lt;/</span>style</span><span uid="3387" class="token punctuation">&gt;</span></span>
      </code></pre></div> <h2 uid="3391">Props</h2> <table uid="3394"><thead uid="3395"><tr uid="3396"><th uid="3397">属性</th> <th uid="3400">类型</th> <th uid="3403">默认值</th> <th uid="3406">必填</th> <th uid="3409">说明</th></tr></thead> <tbody uid="3412"><tr uid="3413"><td uid="3414">size</td> <td uid="3417"><code uid="3418">string</code></td> <td uid="3421"><code uid="3422">default</code></td> <td uid="3425">否</td> <td uid="3428">按钮尺寸，可选值：<code uid="3430">default | mini | large</code></td></tr> <tr uid="3433"><td uid="3434">type</td> <td uid="3437"><code uid="3438">string</code></td> <td uid="3441"><code uid="3442">default</code></td> <td uid="3445">否</td> <td uid="3448">按钮类型，可选值：<code uid="3450">primary | default | warn | danger | text</code></td></tr> <tr uid="3453"><td uid="3454">plain</td> <td uid="3457"><code uid="3458">boolean</code></td> <td uid="3461"><code uid="3462">false</code></td> <td uid="3465">否</td> <td uid="3468">按钮是否镂空，背景色透明</td></tr> <tr uid="3471"><td uid="3472">disabled</td> <td uid="3475"><code uid="3476">boolean</code></td> <td uid="3479"><code uid="3480">false</code></td> <td uid="3483">否</td> <td uid="3486">是否禁用</td></tr> <tr uid="3489"><td uid="3490">loading</td> <td uid="3493"><code uid="3494">boolean</code></td> <td uid="3497"><code uid="3498">false</code></td> <td uid="3501">否</td> <td uid="3504">名称前是否带 loading 图标</td></tr> <tr uid="3507"><td uid="3508">block</td> <td uid="3511"><code uid="3512">boolean</code></td> <td uid="3515"><code uid="3516">false</code></td> <td uid="3519">否</td> <td uid="3522">按钮是否为块级元素,自适应父级元素宽度</td></tr> <tr uid="3525"><td uid="3526">form-type</td> <td uid="3529"><code uid="3530">string</code></td> <td uid="3533">-</td> <td uid="3536">否</td> <td uid="3539"><code uid="3540">submit | reset</code></td></tr></tbody></table></article>`
    }
  ]
})
